language: node_js
node_js:
  - stable
install:
  - npm install -g codecov
  - npm i -g gatsby
script:
  - yarn install
  - yarn lint
  - yarn test:coverage --runInBand --no-cache
  - yarn test --runInBand --no-cache
  - codecov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: source
after_success:
  - yarn deploy
cache:
  directories:
    - node_modules
